# Generated by Django 2.0 on 2017-12-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('weight', models.FloatField()),
                ('duration', models.DurationField()),
                ('deadline', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DreamDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_dependency', to='manageDreams.Dream')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_dependent', to='manageDreams.Dream')),
            ],
        ),
        migrations.CreateModel(
            name='DreamFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dreamFiles/')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDreams.Dream')),
            ],
        ),
        migrations.CreateModel(
            name='DreamHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_dream', to='manageDreams.Dream')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_dream', to='manageDreams.Dream')),
            ],
        ),
        migrations.CreateModel(
            name='DreamProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField()),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDreams.Dream')),
            ],
        ),
    ]
